on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to tiecd
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Deploy
        id: hello
        uses: dataaxiom/tiecd-deploy-action@main
        with:
          who-to-greet: 'Mona the Octocat'
