on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to tiecd
    steps:
      - name: pwd
        run: echo `pwd`
      - name: Deploy
        id: hello
        uses: dataaxiom/tiecd-deploy-action@main
        with:
          who-to-greet: 'Mona the Octocat'
