on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to tiecd
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Deploy
        uses: dataaxiom/tiecd-deploy-action@main
        with:
          apps: keycloak
          files: 'rohan.yml'
