on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to tiecd
    steps:
      - name: Deploy
        id: hello
        uses: dataaxiom/tiecd-deploy-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
