on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A job to tiecd
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: ls
        run: ls -al
      - name: pwd
        run: echo `pwd`
      - name: Deploy
        id: hello
        uses: dataaxiom/tiecd-deploy-action@main
        with:
          files: 'rohan.yml'
